config/routes.rb
Rails.application.routes.draw do
  resources :audio_messages, only: %i[index show new create destroy]
  resources :comments, only: %i[index create update destroy]
  resources :resistenfant, :controller => 'users', only: %i[show]
  devise_for :users, controllers: { confirmations: 'confirmations' }
  get 'about', to: 'pages#about'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :audio_messages, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum avatar: [ :gohan, :goku, :vegeta, :krillin ]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :grade, inclusion: { in: %w(Caporale Sergent Adjudant Major Lieutenant Capitaine Colonel Général),
    message: "%{grade} n'est pas un grade autorisé !" }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @audio_messages = AudioMessage.where(user_id: params[:id])
  end
end

app/views/users/show.html.erb
<div class="page-container">
  <div class="page user">
    <!-- White card handling infos and avatar -->
      <!-- avatar -->
      <div class="video-container">
          <% if @user.avatar.nil? %>
            <%= image_tag "avatars/krillin.jpeg", class: "big-avatar" %>
          <% else %>
            <%= image_tag "avatars/#{@user.avatar}.jpeg", class: "big-avatar" %>
          <% end %>
      </div>
      <!-- container where user text infos are displayed -->
      <div class="infos_container">
        <div class="title">
          <h4>Fiche du raizistant</h4>
        </div>

        <div class="username">
          <h4><%= @user.pseudo %></h4>
          <p><%= @user.grade %></p>
        </div>

        <div class="user-mail">
          <h4>Email</h4>
          <p><%= @user.email %></p>
        </div>

        <div class="text">
          <p>phrase rigolote histoire de combler le vide et patati et patata
            patati patata bla bla bla...
          </p>
        </div>
      </div>
  </div>
  <div class="audio-container">
  <!-- add audio message card -->
  <div class="new-message">
    <!-- text -->
    <div class="mes-messages">
      <h2>Mes messages</h2>
      <p>Les discours que tu as fait</p>
    </div>
    <!-- link to aduio messages new -->
    <div class="add-audio-message">
      <%= link_to "Ajouter un nouveau message", new_audio_message_path %>
    </div>
  </div>
  
  <!-- audio messages cards -->
  <div class="audio-cards">
    <% @audio_messages.each do |audio_message| %>
      <div class="audio-card">
        <!-- avatar -->
        <div class="image">
          <% if @user.avatar.nil? %>
            <%= image_tag "avatars/krillin.jpeg", class: "little-avatar" %>
          <% else %>
            <%= image_tag "avatars/#{@user.avatar}.jpeg", class: "little-avatar" %>
          <% end %>
        </div>
        <!-- user pseudo & audio container -->
        <div class="pseudo-and-audio">
          <!-- user infos -->
          <div class="username">
            <h3><%= @user.pseudo %></h3>
            <p><%= @user.grade %></p>
          </div>
          <!-- audio message -->
          <div class="player">
            <% if audio_message.audio_file.attached? == false %>
              <p>Pas d'audio</p>
            <% else %>
              <%= audio_tag rails_blob_path(audio_message.audio_file), controls: true %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>


<!-- Background -->
<%= render 'shared/background' %>