config/routes.rb
Rails.application.routes.draw do
  resources :audio_messages, only: %i[index show new create destroy]
  resources :comments, only: %i[index create update destroy]
  resources :resistenfant, :controller => 'users', only: %i[show]
  devise_for :users, controllers: { confirmations: 'confirmations' }
  get 'about', to: 'pages#about'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_audio_card.html.erb
<!-- Template de Card pour les commentaires des audios -->

<% @audio_messages.each do |audio_message| %>
  <div class="audio-card">
    <div class="audio-card-avatar">
      <% if audio_message.user.avatar.nil? %>
        <%= image_tag "avatars/krillin.jpeg" %>
      <% else %>
        <%= image_tag "avatars/#{audio_message.user.avatar}.jpeg" %>
      <% end %>
    </div>
    <div class="audio-card-body">
      <div class="identity">
        <h4 class="pseudo">
          <%= link_to audio_message.user.pseudo, resistenfant_path(audio_message.user.id), class: "user-link" %>
        </h4>
        <h6 class="grade">
          <%= audio_message.user.grade %>
        </h6>
      </div>
      <div class="player">
        <% if audio_message.audio_file.attached? == false %>
          <p>Pas d'audio</p>
        <% else %>
          <%= audio_tag rails_blob_path(audio_message.audio_file), controls: true %>
        <% end %>
      </div>
      <button class="comments-btn">
        commentaires
        <i class="far fa-eye"></i>
      </button>
    </div>
  <!-- Section Commentaires Default Display: None -->
  </div>
  <div class="audio-card-comments">
    <!-- Form ajout commentaire -->
    <div class="message-form">
      <form class="search-form f<%= audio_message.id %>" data-audio-message-id="<%= audio_message.id %>">
        <input class="form" type="text" placeholder="Donnes tes impressions sur le message audio !" aria-label="Commentaire">
        <input type="submit" value="Oui chef !" class="submit-button">
      </form>
    </div>
    <!-- List des commentaires -->
    <div id="comments-list-<%= audio_message.id %>" class="comments-list">
      <% @comments.each do |comment| %>
        <% if comment.audio_message_id == audio_message.id %>
          <%= render "comments/comment", comment: comment, user: comment.user %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_background.html.erb
<!-- Hide background overflow -->
<div class="mask">
<!-- Background -->
<div class="body-background">
    <div class="folder-content">
        <!-- Shadow -->
        <div class="shadow-page"></div>
        <div class="page">
            <!-- Text -->
            <h4>On est là papa.</h4>
            <p>Tu vas faire quoi?</p>
            <!-- Polaroid -->
            <div id="first"class="photo-container">
                <%= image_tag('photo4.jpg', class: 'photo') %>
            </div>
        </div>
    </div>

    <!-- Folder -->
    <div class="folder"></div>
    <!-- <%= image_tag('folder.svg', class: 'folder') %> -->

    <!-- Polaroids -->
    <div id="second" class="photo-container">
        <%= image_tag('photo1.jpg', class: 'photo') %>
    </div>
    <div id="third" class="photo-container">
        <%= image_tag('photo2.jpg', class: 'photo') %>
    </div>
    <div id="fourth" class="photo-container">
        <%= image_tag('photo3.jpg', class: 'photo') %>
    </div>

    <!-- Back elements -->
    <%= image_tag('pencil.svg', class: 'pencil') %>
    <%= image_tag('flower.svg', class: 'flower') %>
    <%= image_tag('scribbles.svg', class: 'scribbles') %>
    <%= image_tag('stickman.svg', class: 'stickman') %>

    <div class="back-gradient"></div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%= link_to root_path do %>
<%= image_tag('logo.svg', class:'logo') %>
<% end %>
<div class="bg-logo"></div>

<!-- Assets Le Wagon -->

<!-- <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
  <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div> -->